---
- name: Include OS family specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"

- include_tasks: nginx_pre.yml
- include_tasks: nginx_install.yml

- block: # Config Nginx
  - include_tasks: nginx_search_config.yml
  - include_tasks: nginx_post.yml
  tags:
    - nginx-config
