---
- name: Install Nginx (Debian/Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    name: "{{ nginx_apt_package }}"
    state: present
    update_cache: yes

- name: Install Nginx (RedHat)
  when: ansible_os_family == "RedHat"
  yum:
    name: "{{ nginx_yum_package }}"
    state: present
    update_cache: yes

- name: Make sure Nginx start
  systemd:
    name: nginx
    state: started
    enabled: yes
