---
- name: Ensure gpg binary is installed (Ubuntu/Debian)
  apt:
    name: gnupg
    update_cache: yes
  when:
    - ansible_os_family == 'Debian'

- name: Add Nginx repository key from keyfile (Ubuntu/Debian)
  apt_key:
    url: "{{ nginx_apt_key_url }}"
    state: present
  when:
    - ansible_os_family == 'Debian'
    - nginx_apt_key_use_upstream is defined
    - nginx_apt_key_use_upstream

- name: Add Nginx repository key (un-proxy environment) (Ubuntu/Debian)
  apt_key:
    keyserver: "{{ nginx_apt_key_server }}"
    id: "{{ nginx_apt_key_id }}"
  when:
    - ansible_os_family == 'Debian'
    - nginx_apt_key_use_upstream is defined
    - not nginx_apt_key_use_upstream
    - proxy_env is not defined

# apt-key with proxy need to use command
# https://github.com/ansible/ansible/issues/31691#issuecomment-396973282
- name: Add Nginx repository key (proxy environment) (Ubuntu/Debian)
  command: |
    apt-key adv --keyserver-options http-proxy={{ proxy_env.http_proxy }} \
    --fetch-keys 'http://{{ nginx_apt_key_server }}/pks/lookup?op=get&search=0x{{ nginx_apt_key_id }}'
  when:
    - ansible_os_family == 'Debian'
    - nginx_apt_key_use_upstream is defined
    - not nginx_apt_key_use_upstream
    - proxy_env is defined

- name: Add Nginx repository (Ubuntu/Debian)
  apt_repository:
    repo: "{{ nginx_apt_repo }}"
  when: ansible_os_family == 'Debian'

- name: Add Nginx repository (CentOS/RHEL)
  yum_repository:
    name: nginx
    description: "Nginx YUM repository"
    baseurl: "{{ nginx_yum_repo }}"
    gpgkey: "{{ nginx_yum_key_url }}"
  when: ansible_os_family == 'RedHat'