---
- name: Ensure rsync and libsemanage-python is installed (RedHat)
  when: ansible_os_family == "RedHat"
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
    - rsync
    - libsemanage-python

# synchronize module does not work well with sudo with password
# https://github.com/ansible/ansible/issues/20769#issuecomment-321341370
- name: Allow rsync without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: present
    insertafter: '^%sudo'
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
    validate: 'visudo -cf %s'
  when: nginx_config_check.stat.exists

# rsync nginx configuration except ssl directory
- name: Copy Nginx configuration file
  synchronize:
    src: "{{ nginx_host_config_path }}/"
    dest: "{{ nginx_config_path }}/"
    delete: yes
    rsync_opts:
      - "--exclude=ssl"
  when: nginx_config_check.stat.exists
  notify: Check nginx configuration and reload nginx

- name: Disallow rsync without SUDO password
  lineinfile:
    path: /etc/sudoers
    state: absent
    line: "{{ ansible_user }} ALL=NOPASSWD: /usr/bin/rsync"
    validate: 'visudo -cf %s'
  when: nginx_config_check.stat.exists

- name: Copy SSL certificates directory
  copy:
    src: "{{ nginx_host_config_path }}/ssl"
    dest: "{{ nginx_config_path }}/"
  when:
    - nginx_config_ssl_check.stat.isdir is defined
    - nginx_config_ssl_check.stat.isdir
  notify: Check nginx configuration and reload nginx

- name: Enable seboolean to enable nginx reverse proxy (RedHat)
  when: ansible_os_family == "RedHat"
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
