---
- name: Install Nginx (Ubuntu/Debian)
  apt:
    name: "{{ nginx_package_name }}"
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install Nginx (CentOS/RHEL)
  yum:
    name: "{{ nginx_package_name }}"
    state: present
  when: ansible_os_family == 'RedHat'

- name: Ensure service is enabled
  systemd:
    name: "{{ nginx_service_name }}"
    state: started
    enabled: yes
